# Generated by Django 2.0.5 on 2018-06-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oler', '0004_auto_20180615_0600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RiderHistory',
            new_name='RideHistory',
        ),
    ]
