# Generated by Django 2.0.5 on 2018-06-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oler', '0009_auto_20180615_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_state', models.IntegerField(choices=[(1, 'requested'), (2, 'accepted'), (3, 'ongoing'), (4, 'completed'), (5, 'rejected')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ridehistory',
            name='ride_state',
        ),
        migrations.AddField(
            model_name='ridehistory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='DriverProfile',
        ),
        migrations.AddField(
            model_name='ridetrack',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='oler.RideHistory'),
        ),
    ]
