# Generated by Django 2.0.5 on 2018-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oler', '0010_auto_20180617_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridehistory',
            name='seats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
