# Generated by Django 2.0.5 on 2018-06-17 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oler', '0012_auto_20180617_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridetrack',
            name='rider',
        ),
        migrations.AddField(
            model_name='ridehistory',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider', to=settings.AUTH_USER_MODEL),
        ),
    ]
